version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/workflow_builder
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - workflow-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=workflow_builder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - workflow-network

volumes:
  postgres_data:

networks:
  workflow-network:
    driver: bridge
